service:
  name: auction-service

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    AuctionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S 
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  bundle:
    linting: false
